name: dgplay
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+2

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  device_info_plus: ^10.1.0
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  path_provider: ^2.1.3
  carousel_slider: ^5.0.0
  connectivity_plus: ^6.0.3
  flutter_cache_manager: ^3.3.2
  firebase_core: ^3.5.0
  cloud_firestore: ^5.4.2
  video_player: ^2.10.0
  video_compress: ^3.1.4
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.6
  cached_video_player_plus: ^4.0.0
#  platform_device_id: ^1.0.1
  android_intent_plus: ^5.1.0
  flutter_widget_from_html: ^0.15.0

  flutter_html_iframe: ^3.0.0-beta.2
  webview_flutter: ^4.7.0
  xml2json: ^6.2.3
  chewie: ^1.10.0
  media_kit: ^1.2.0
  media_kit_video: ^1.3.0
  media_kit_libs_video: ^1.0.6
  http: ^1.4.0
  ota_update: ^7.0.2

#  huawei_ads: ^13.4.67+302
#  platform_device_id_v3: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/
